apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: student-system
type: Opaque
stringData:
  # Diganti sesuai docker-compose.yml Anda
  MONGO_URL: "mongodb://mongodb-service:27017" 
  JWT_SECRET_KEY: "kunci_rahasia_uts_docker" 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: student-system
data:
  DB_NAME: "student_management_db"
  # CORS Origin agar frontend (via Ingress) bisa akses backend
  CORS_ORIGINS: "http://student.local,http://localhost"