apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-ingress
  namespace: student-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: student.local
    http:
      paths:
      # --- PERBAIKAN ---
      # Ubah regex dari /api/(.*) menjadi /(api/.*)
      # Tujuannya agar kata "api" ikut tertangkap dan dikirim ke backend
      - path: /(api/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 8001
      # -----------------
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 3000